"""attach identity to argos id columns

Revision ID: 4e6fd070e722
Revises: e0ed4a2c7c0f
Create Date: 2026-08-14 16:48:44.791740

On the real database, argos_market_history.id and argos_metrics.id are plain
BIGINT PRIMARY KEY columns with no sequence/identity/default - confirmed via
information_schema.columns (column_default empty, is_identity = 'NO').
Without this, every INSERT fails with a NOT NULL violation on id.

This attaches an identity to the existing column (equivalent to a bigserial),
without dropping or renaming anything. Idempotent: swallows the error if the
column already has some default/identity. Mirrors section 0 of
docs/argos_market_migration.sql - keep both in sync if this ever changes.
"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4e6fd070e722'
down_revision: Union[str, None] = 'e0ed4a2c7c0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        DO $$
        BEGIN
            ALTER TABLE argos_market_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
        EXCEPTION
            WHEN others THEN
                NULL; -- already has a default/identity - nothing to do
        END $$;
        """
    )
    op.execute(
        """
        DO $$
        BEGIN
            ALTER TABLE argos_metrics ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
        EXCEPTION
            WHEN others THEN
                NULL; -- already has a default/identity - nothing to do
        END $$;
        """
    )


def downgrade() -> None:
    op.execute("ALTER TABLE argos_market_history ALTER COLUMN id DROP IDENTITY IF EXISTS")
    op.execute("ALTER TABLE argos_metrics ALTER COLUMN id DROP IDENTITY IF EXISTS")
