-- ============================================================================
-- ARGOS - Módulo Mercado - migration manual (SQL puro, sem Alembic)
--
-- Espelha as migrations Alembic 19dc5ecf6ad7, e0ed4a2c7c0f, 4e6fd070e722 e
-- 2340a66a9f58, mais a correção da seção 0, descobertas ao validar contra a
-- estrutura real. Seguro rodar de novo mesmo que as seções 0-2 já tenham
-- sido aplicadas antes - IF NOT EXISTS em tudo. Executar direto no SQL
-- Editor do DBeaver, conectado ao banco "features", schema "public".
--
-- GARANTIAS:
--   - só toca em public.argos_market_history e public.argos_metrics;
--   - a única mudança em coluna já existente é anexar identity a "id"
--     (seção 0, necessária - sem ela nenhum INSERT funciona; ver detalhes
--     lá); todo o resto é ADD COLUMN IF NOT EXISTS / CREATE INDEX IF NOT EXISTS;
--   - nenhum DROP, nenhuma outra tabela é referenciada;
--   - idempotente: pode rodar mais de uma vez sem erro e sem efeito colateral.
--
-- IMPORTANTE: antes de rodar, confirme que está conectado ao banco/schema
-- corretos (rode a query abaixo isoladamente primeiro, se quiser conferir):
--
--   SELECT current_database(), current_schema();
--   -- deve retornar: features | public
--
-- ============================================================================


-- ----------------------------------------------------------------------------
-- 0) Correção necessária: "id" hoje é BIGINT PRIMARY KEY sem sequence/identity
--    (confirmado via information_schema.columns: column_default vazio,
--    is_identity = 'NO'). Sem isso, TODO insert falha com
--    "null value in column id violates not-null constraint", porque nada
--    gera o próximo valor de id automaticamente.
--
--    A correção anexa uma IDENTITY à coluna já existente (equivalente a um
--    bigserial) - não cria coluna nova, não apaga dado, é reversível
--    (ALTER TABLE ... ALTER COLUMN id DROP IDENTITY) e é ignorada
--    silenciosamente se a coluna já tiver algum default/identity (idempotente).
-- ----------------------------------------------------------------------------

DO $$
BEGIN
    ALTER TABLE public.argos_market_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
EXCEPTION
    WHEN others THEN
        NULL; -- já tem default/identity - nada a fazer
END $$;

DO $$
BEGIN
    ALTER TABLE public.argos_metrics ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
EXCEPTION
    WHEN others THEN
        NULL; -- já tem default/identity - nada a fazer
END $$;


-- ----------------------------------------------------------------------------
-- 1) public.argos_market_history
--    Transforma a tabela (hoje só com "id") numa série genérica de mercado.
-- ----------------------------------------------------------------------------

ALTER TABLE public.argos_market_history ADD COLUMN IF NOT EXISTS source TEXT;
ALTER TABLE public.argos_market_history ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE public.argos_market_history ADD COLUMN IF NOT EXISTS asset TEXT;
ALTER TABLE public.argos_market_history ADD COLUMN IF NOT EXISTS symbol TEXT;
ALTER TABLE public.argos_market_history ADD COLUMN IF NOT EXISTS metric TEXT;
ALTER TABLE public.argos_market_history ADD COLUMN IF NOT EXISTS value NUMERIC;
ALTER TABLE public.argos_market_history ADD COLUMN IF NOT EXISTS reference_date DATE;
ALTER TABLE public.argos_market_history ADD COLUMN IF NOT EXISTS expiration_date DATE;
ALTER TABLE public.argos_market_history ADD COLUMN IF NOT EXISTS metadata JSONB;
ALTER TABLE public.argos_market_history
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;


-- ----------------------------------------------------------------------------
-- 2) public.argos_metrics
--    Mesma lógica genérica de argos_market_history, para os indicadores
--    agregados (variações, vértices de curva, inclinação, etc).
-- ----------------------------------------------------------------------------

ALTER TABLE public.argos_metrics ADD COLUMN IF NOT EXISTS source TEXT;
ALTER TABLE public.argos_metrics ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE public.argos_metrics ADD COLUMN IF NOT EXISTS asset TEXT;
ALTER TABLE public.argos_metrics ADD COLUMN IF NOT EXISTS symbol TEXT;
ALTER TABLE public.argos_metrics ADD COLUMN IF NOT EXISTS metric TEXT;
ALTER TABLE public.argos_metrics ADD COLUMN IF NOT EXISTS value NUMERIC;
ALTER TABLE public.argos_metrics ADD COLUMN IF NOT EXISTS reference_date DATE;
ALTER TABLE public.argos_metrics ADD COLUMN IF NOT EXISTS metadata JSONB;
ALTER TABLE public.argos_metrics
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public.argos_metrics
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;


-- ----------------------------------------------------------------------------
-- 3) Índices
--    Um índice por coluna de filtro frequente, mais um índice único (por
--    tabela) para evitar duplicidade lógica da mesma série/data.
-- ----------------------------------------------------------------------------

-- argos_market_history
CREATE INDEX IF NOT EXISTS ix_argos_market_history_reference_date
    ON public.argos_market_history (reference_date);
CREATE INDEX IF NOT EXISTS ix_argos_market_history_asset
    ON public.argos_market_history (asset);
CREATE INDEX IF NOT EXISTS ix_argos_market_history_symbol
    ON public.argos_market_history (symbol);
CREATE INDEX IF NOT EXISTS ix_argos_market_history_category
    ON public.argos_market_history (category);

-- argos_metrics
CREATE INDEX IF NOT EXISTS ix_argos_metrics_reference_date
    ON public.argos_metrics (reference_date);
CREATE INDEX IF NOT EXISTS ix_argos_metrics_asset
    ON public.argos_metrics (asset);
CREATE INDEX IF NOT EXISTS ix_argos_metrics_symbol
    ON public.argos_metrics (symbol);
CREATE INDEX IF NOT EXISTS ix_argos_metrics_category
    ON public.argos_metrics (category);


-- ----------------------------------------------------------------------------
-- 4) Índices únicos NULL-safe (necessários para upsert atômico e concorrente)
--
--    expiration_date é nullable (séries macro/juros não têm vencimento) e o
--    Postgres trata todo NULL como distinto num índice único simples - dois
--    registros da MESMA série/data com expiration_date NULL NÃO violavam o
--    índice antigo, permitindo duplicidade. O mesmo vale para "symbol" em
--    argos_metrics (métricas no nível do ativo, ex. vértices de curva, não
--    têm symbol). Confirmado empiricamente antes de escrever esta correção.
--
--    Por isso o índice único agora usa COALESCE para um valor-sentinela,
--    fazendo NULL comparar como igual a si mesmo para fins de unicidade -
--    e é exatamente esse o alvo (conflict target) do
--    INSERT ... ON CONFLICT usado em market_repository.py.
--
--    Se as versões antigas (sem COALESCE) já existirem de uma aplicação
--    anterior deste arquivo, o DROP + CREATE abaixo as substitui - só o
--    índice muda, nenhum dado é tocado.
-- ----------------------------------------------------------------------------

DROP INDEX IF EXISTS uq_argos_market_history_series;
CREATE UNIQUE INDEX IF NOT EXISTS uq_argos_market_history_series
    ON public.argos_market_history (
        source, category, asset, symbol, metric, reference_date,
        COALESCE(expiration_date, DATE '0001-01-01')
    );

DROP INDEX IF EXISTS uq_argos_metrics_series;
CREATE UNIQUE INDEX IF NOT EXISTS uq_argos_metrics_series
    ON public.argos_metrics (category, asset, COALESCE(symbol, ''), metric, reference_date);


-- ============================================================================
-- Fim. Para conferir o resultado, rode:
--
--   SELECT column_name, data_type, is_nullable
--   FROM information_schema.columns
--   WHERE table_schema = 'public' AND table_name = 'argos_market_history'
--   ORDER BY ordinal_position;
--
--   SELECT column_name, data_type, is_nullable
--   FROM information_schema.columns
--   WHERE table_schema = 'public' AND table_name = 'argos_metrics'
--   ORDER BY ordinal_position;
-- ============================================================================
